### ISSUE TITLE
Could not import faiss-node

### ISSUE THREAD

**Issue by tylangesmith** [hwchase17/langchainjs#2107] opened 2023-07-28 00:10 UTC
Hey there,

I'm trying to use the `FaissStore.loadFromPython` function to load an existing FAISS vector store. However I'm getting the following error:

```
Error: Could not import faiss-node. Please install faiss-node as a dependency with, e.g. `npm install -S faiss-node`.

Error: Cannot read properties of undefined (reading 'indexOf')
```
![Screenshot 2023-07-28 at 10 07 25 am](https://github.com/hwchase17/langchainjs/assets/22609577/90af7c63-3e2a-4949-ad3c-9422632891ce)

I'm running on a M1 macbook.

**Comment by jacoblee93** [comment] 2023-07-28 21:26
This looks like an Edge environment? It's unfortunately Node only :(

**Comment by tylangesmith** [comment] 2023-07-29 09:25
> This looks like an Edge environment? It's unfortunately Node only :(

I'm getting the above error running on my Macbook pro running a NextJS app.

**Comment by jacoblee93** [comment] 2023-07-29 16:35
Can you give any other details for @ewfian?

**Comment by ewfian** [comment] 2023-08-04 05:25
May relates to https://github.com/hwchase17/langchainjs/issues/1976#issuecomment-1646861393
I have checked, the `loadFromPython` won't work with the index file saved from langchain 0.0.123.
Because the `document` changed from `langchain.docstore.document` to `langchain.schema.document` in (https://github.com/langchain-ai/langchain/commits/812419d946daf8e10f07fcd1ea03567ec7f287ad/libs/langchain/langchain/schema/document.py)

I will fix it, @jacoblee93 Please assign this issue to me.

**Comment by jacoblee93** [comment] 2023-08-04 13:48
Got it, thank you!

I wonder if there's a better way to do the mapping in the future - I don't think there should be too many more namespace changes though.

**Comment by ewfian** [comment] 2023-08-06 09:13
@jacoblee93 I haven't come up with a better way to handle the mapping at the moment, as the serialized pickle uses string namespaces to label the structure. We need to establish the correlation between this structure and JS objects, and it appears that hardcoding might be the only option.  However, as you mentioned, structural changes are likely to be infrequent, so the current approach should be fine.

**Closed** 2023-08-07 02:30 UTC
Labels: auto:bug

**Comment by TimofeyBiryukov** [comment] 2023-08-15 06:58
Having the same issue.
Mac M1 Ventura 13.4.1
Node - v18.15.0
NPM - 9.5.0
langchain - 0.0.127
faiss-node (installed with `npm i faiss-node`) - 0.3.0

**Comment by ewfian** [comment] 2023-08-15 07:06
@TimofeyBiryukov Can you share more details like error log or sample code to reproduce?

**Comment by ewfian** [comment] 2023-08-15 10:13
@TimofeyBiryukov It should be works on latest node:18 arm64.
Noticed that your Node.js version is v18.13.0, its not the latest version, try `docker pull node:18` to update you local cached image and try again.

I just add a check here: https://github.com/ewfian/faiss-node/actions/runs/5865662923/job/15902994543
and found that `faiss-node` works well on latest node:18 arm64.


The `faiss-node` for linux arm64 was built on node:18-bookworm, so it won't work on versions lower than `bookworm`
https://askubuntu.com/questions/445487/what-debian-version-are-the-different-ubuntu-versions-based-on

**Comment by TimofeyBiryukov** [comment] 2023-08-15 10:24
@ewfian huh, you're completely right.
I could swear I tried `node:18` while poking around.
You did definitely clear it up for me, thanks!

**Comment by Simbaclaws** [comment] 2024-01-14 23:14
Hi there,

I'm getting the same type of error message in my console when I try to:
```javascript
const vectorstore = await FaissStore.load("./knowledge", new OpenAIEmbeddings({
            modelName: "text-embedding-ada-002"
}));
```

knowledge is a folder in the root folder that includes 2 files:
```
index.pkl
index.faiss
```

I am using the following to see whether my API route in nextjs can reach the files:
```javascript
const knowledge = path.resolve('./knowledge');
const filenames = fs.readdirSync(knowledge);
console.log(filenames);
```
this logs the actual filenames, so I know they're there...

I'm getting the following error message in my console:
```
Error: Could not import faiss-node. Please install faiss-node as a dependency with, e.g. `npm install -S faiss-node`.

Error: Cannot read properties of undefined (reading 'indexOf')
    at FaissStore.importFaiss (webpack-internal:///(rsc)/./node_modules/@langchain/community/dist/vectorstores/faiss.js:363:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async readIndex (webpack-internal:///(rsc)/./node_modules/@langchain/community/dist/vectorstores/faiss.js:234:37)   
    at async Promise.all (index 1)
    at async FaissStore.load (webpack-internal:///(rsc)/./node_modules/@langchain/community/dist/vectorstores/faiss.js:237:51)
    at async POST (webpack-internal:///(rsc)/./app/api/chat/route.ts:56:29)
    at async D:\Development\Persoonlijk\gpt-creator\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:63251
```

I'm running this on windows with ```npm run dev```

**Comment by amrsa1** [comment] 2024-10-16 09:11
What was the solution ?

**Comment by CookieTheP** [comment] 2025-03-04 15:22
Hello everyone.
I've got the same issue when deploying nodejs code as an aws fargate service.
On the local machine this does not happen.
Anyone has got a solution so far?

**Comment by ChalkleyZhou** [comment] 2025-03-07 03:31
I tried pnpm@9, it works. but pnpm@10 got the same issue.

**Comment by ChalkleyZhou** [comment] 2025-03-07 03:53
> I tried pnpm@9, it works. but pnpm@10 got the same issue.

that is because pnpm@10 won't postinstall the package like 'faiss-node'.

should add the code behind.

`
"pnpm": {
    "onlyBuiltDependencies": [
      "faiss-node"
    ]
 }
`

and i think, maybe the same problem with npm

**Comment by KokoDoko** [comment] 2025-09-18 09:12
Same issue with langchain 1.0.0 alpha. It works in Langchain 0.3.
