### ISSUE TITLE
Network Error in `ConversationChain`

### ISSUE THREAD

**Issue by homanp** [hwchase17/langchainjs#739] opened 2023-04-11 11:46 UTC
I'm getting the following `axios` error when calling my `ConversationChain`

### Error
```
"Error: Network Error\n    at createError (webpack-internal:///(api)/./node_modules/langchain/dist/util/axios-fetch-adapter.js:316:19)\n    at getResponse (webpack-internal:///(api)/./node_modules/langchain/dist/util/axios-fetch-adapter.js:197:16)\n    at async fetchAdapter (webpack-internal:///(api)/./node_modules/langchain/dist/util/axios-fetch-adapter.js:174:18)"
```

### Implementation
```
const history = messages.map(({ agent, message }) =>
    agent === "ai" ? new AIChatMessage(message) : new HumanChatMessage(message)
  );

  const memory = new BufferMemory({
    memoryKey: "history",
    chatHistory: new ChatMessageHistory(history),
    returnMessages: true,
  });

  const llm = new ChatOpenAI({
    temperature: 0,
  });

  const prompt = ChatPromptTemplate.fromPromptMessages([
    SystemMessagePromptTemplate.fromTemplate(
      DEFAULT_PROMPT_TEMPLATE
    ),
    new MessagesPlaceholder("history"),
    HumanMessagePromptTemplate.fromTemplate("{message}"),
  ]);

  const chain = new ConversationChain({
    memory,
    prompt,
    llm,
  });

  try {
    response.status(200).json({
      success: true,
      data: await chain.call({
        message,
      }),
      agent: "ai",
    });
  } catch (error) {
    console.log(error);
    response.status(500).json({ success: false, error });
  }
  ```

**Comment by homanp** [comment] 2023-04-11 12:12
Also trid upgrading to 0.0.52 but still get the same error.

**Comment by homanp** [comment] 2023-04-11 12:29
It works properly if one does not use `memory`. So perhaps the something going inside that functionality?

**Comment by homanp** [comment] 2023-04-11 12:46
Also running the same request using `ky` or `cURL` generates the correct response: 

POST:  https://api.openai.com/v1/chat/completions

Data:
```
{
    "model":"gpt-3.5-turbo","temperature":0,"top_p":1,"frequency_penalty":0,"presence_penalty":0,"n":1,"stream":false,"messages":[{"role":"system","content":"\\nAssistant is a large language model trained by OpenAI.\\n\\nAssistant is designed to be able to assist with a wide range of tasks, from answering simple questions to providing in-depth explanations and discussions on a wide range of topics. As a language model, Assistant is able to generate human-like text based on the input it receives, allowing it to engage in natural-sounding conversations and provide responses that are coherent and relevant to the topic at hand.\\n\\nAssistant is constantly learning and improving, and its capabilities are constantly evolving. It is able to process and understand large amounts of text, and can use this knowledge to provide accurate and informative responses to a wide range of questions. Additionally, Assistant is able to generate its own text based on the input it receives, allowing it to engage in discussions and provide explanations and descriptions on a wide range of topics.\\n\\nOverall, Assistant is a powerful tool that can help with a wide range of tasks and provide valuable insights and information on a wide range of topics. Whether you need help with a specific question or just want to have a conversation about a particular topic, Assistant is here to assist.\\n"},{"role":"user","content":"Hello"}]
}
```

**Comment by homanp** [comment] 2023-04-11 12:47
@nfcampos any suggestions on this?

**Comment by homanp** [comment] 2023-04-11 13:54
You can run the code locally by cloning this repo: https://github.com/homanp/langchain-ui/pull/65

Environment is NextJS, hosted on Vercel. 

This happens both locally and on Vercel.

**Comment by homanp** [comment] 2023-04-11 13:54
> Can you tell me more about your environment @homanp ? So that I can try to reproduce this on my end What version of node (if you're using this in node), etc

You can run the code locally by cloning this repo: https://github.com/homanp/langchain-ui/

Environment is NextJS, hosted on Vercel.

This happens both locally and on Vercel.

**Comment by homanp** [comment] 2023-04-11 14:27
> I don't see you passing the OPENAI_API_KEY anywhere, might that be the issue? Also, I'd recommend updating to 0.0.52

Locally I have it in my `.env` file. Again, it works sometimes and doesn't work sometimes, fails sporadically. 

I'll update to 0.0.52 and see if that makes any difference.

**Comment by nfcampos** [comment] 2023-04-11 14:29
If it only fails sometimes then must be an issue with OpenAI? Their API isn't the most stable

**Comment by homanp** [comment] 2023-04-11 14:30
> If it only fails sometimes then must be an issue with OpenAI? Their API isn't the most stable

Might be...

**Comment by homanp** [comment] 2023-04-11 15:05
> I don't see you passing the OPENAI_API_KEY anywhere, might that be the issue? Also, I'd recommend updating to 0.0.52

Upgrading to 0.0.52 made it worse, getting Network Errors on all requests now. Perhaps something with the axios setup and NextJS?

**Comment by arronKler** [comment] 2023-04-11 15:31
> > I don't see you passing the OPENAI_API_KEY anywhere, might that be the issue? Also, I'd recommend updating to 0.0.52
> 
> Upgrading to 0.0.52 made it worse, getting Network Errors on all requests now. Perhaps something with the axios setup and NextJS?
> 
> The raw query works each time using cURL.
> 
> You can see the changes here: https://github.com/homanp/langchain-ui/blob/c60f1b14a0560e2f9f01379c8ae9003f8185876c/pages/api/v1/chatbots/%5BchatbotId%5D/index.js

I also can send my request with cURL and even Chrome web console. But not work with pure Node fetch request. The Node 18 seems like never run `fetch` with network proxy (until I use `proxychains` to force it) in my case. By the way, my computer system is MacOS with M1 chip. I guess it's some kind of issue of Node 18 fetch or M1 ?

**Comment by nfcampos** [comment] 2023-04-11 15:50
If you use a proxy this solution might work for you https://github.com/hwchase17/langchainjs/issues/388#issuecomment-1490421309

**Comment by LarchLiu** [comment] 2023-04-11 15:51
> I also can send my request with cURL and even Chrome web console. But not work with pure Node fetch request. The Node 18 seems like never run `fetch` with network proxy (until I use `proxychains` to force it) in my case. By the way, my computer system is MacOS with M1 chip. I guess it's some kind of issue of Node 18 fetch or M1 ?

In my case, if pass `httpsAgent` to `baseOptions` like below (and set `adapter` to `null`), it works.

```
OpenAIChat({
      temperature,
      openAIApiKey: apiKey
    }, {
      basePath,
      baseOptions: {
            httpsAgent: agent,
            adapter: null
          }
    })
```
But it can't support stream in this way.

**Comment by LarchLiu** [comment] 2023-04-11 15:52
> If you use a proxy this solution might work for you [#388 (comment)](https://github.com/hwchase17/langchainjs/issues/388#issuecomment-1490421309)

This is the best solution for me.

**Comment by homanp** [comment] 2023-04-11 20:32
@nfcampos I moved the api route to `NextJS` route handlers and everything seems to work fine.

**Comment by jacob-ruiz** [comment] 2023-04-12 00:25
I'm getting the same error concerning `axios-fetch-adapter` ever since updating langchain to `0.0.53`. I don't have this issue in my other project using `0.0.51`. Both are using Next.js (both using api routes, not route handlers).

**Comment by rawsh** [comment] 2023-04-12 04:31
@homanp Do you mind giving some snippets of how you got that to work? I tried a route handler and I was getting a ton of module errors when calling the chain.

I'm getting consistant network errors when using a regular api route. Mostly on embeddings when I am testing locally, but on every request when deployed to fly.

**Comment by nfcampos** [comment] 2023-04-12 05:22
We actually test with NextJs before each release inside this repo, and I can confirm openai requests work in frontend components, api routes in serverless mode and api routes in edge mode. https://github.com/hwchase17/langchainjs/tree/main/test-exports-vercel/src/pages/api

I can also link you to this project which is using both of those (and the author tells me it works both locally and when deployed to vercel and fly.io) https://github.com/PineappleExpress808/lex-gpt/tree/main/pages/api

Do you want to compare your projects to this, and let me know what's different about yours? As it stands I cannot reproduce this issue, therefore can't help

**Comment by rawsh** [comment] 2023-04-13 05:24
@nfcampos Thank you for the link. I've isolated the error to loading pinecone, which fails with

```
error - node:fs/promises
Module build failed: UnhandledSchemeError: Reading from "node:fs/promises" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
Import trace for requested module:
node:fs/promises
./node_modules/.pnpm/langchain@0.0.53_@huggingface+inference@1.7.1_@pinecone-database+pinecone@0.0.10_chromadb@1.3_jkokrjsyutt3gmckgig32mu37u/node_modules/langchain/dist/vectorstores/hnswlib.js
./node_modules/.pnpm/langchain@0.0.53_@huggingface+inference@1.7.1_@pinecone-database+pinecone@0.0.10_chromadb@1.3_jkokrjsyutt3gmckgig32mu37u/node_modules/langchain/dist/vectorstores/index.js
./node_modules/.pnpm/langchain@0.0.53_@huggingface+inference@1.7.1_@pinecone-database+pinecone@0.0.10_chromadb@1.3_jkokrjsyutt3gmckgig32mu37u/node_modules/langchain/vectorstores.js
```

To reproduce just load a PineconeStore in `hello-edge.ts`.

**Comment by nfcampos** [comment] 2023-04-13 05:44
That looks like you are importing from langchain/vectorstores which was deprecated, see https://js.langchain.com/docs/getting-started/install 
If instead you import it from langchain/vectorstores/pinecone it might work, give it a try and let me know

**Comment by rawsh** [comment] 2023-04-13 15:24
@nfcampos Thank you for the tip, that fixes the langchain related import errors. 

Unrelated but I'll leave a comment in case someone else has the same issue. Looks like I was running into an edge case that comes up when using top level await in an edge function. The following pattern for importing pinecone fails with `The Edge Function "pages/api/vectordbqa" must export a `default` function`. Simply moving the init logic inside the handler fixes the issue.

```
async function initializePinecone() {
  // connect to pinecone
  const client = new PineconeClient();

  await client.init({
  apiKey: process.env.PINECONE_API_KEY || "",
  environment: process.env.PINECONE_ENVIRONMENT || "",
  });

  client.projectName = process.env.PINECONE_PROJECT_NAME || "";
  return client
}

export const pinecone = await initializePinecone()
```

**Comment by aseem2625** [comment] 2023-04-19 10:48
@rawsh Facing same issue, I am using vercel edge functions.

```
error  [ErrorWithoutStackTrace: PineconeClient: Error getting project name: Error: A Node.js API is used (process.nextTick) which is not supported in the Edge Runtime.

error - The Edge Function "pages/api/chat" must export a `default` function
null
error - utils/pinecone-client.ts (19:10) @ initPinecone
error - unhandledRejection: Failed to initialize Pinecone Client
  17 |   } catch (error) {
  18 |     console.log('error', error);
> 19 |     throw new Error('Failed to initialize Pinecone Client');
     |          ^
  20 |   }
  21 | }
  22 | 

```

Pinecone-client.js looks similar as yours
```
import { PineconeClient } from '@pinecone-database/pinecone';

if (!process.env.PINECONE_ENVIRONMENT || !process.env.PINECONE_API_KEY) {
  throw new Error('Pinecone environment or api key vars missing');
}

export async function initPinecone() {
  try {
    const pinecone = new PineconeClient();

    await pinecone.init({
      environment: process.env.PINECONE_ENVIRONMENT ?? '',
      apiKey: process.env.PINECONE_API_KEY ?? '',
    });

    return pinecone;
  } catch (error) {
    console.log('error', error);
    throw new Error('Failed to initialize Pinecone Client');
  }
}

export const pinecone = await initPinecone();
```


Error is due to PineconeClient, moving this inside handler function is not helping either.

Can you share code what exactly worked for you?

**Comment by ai-slave** [comment] 2023-04-28 13:20
Importing fetch at the start of the ```axios-fetch-adapter.js``` helped fix this for me. 
```import fetch from "node-fetch";```

**Comment by rawsh** [comment] 2023-04-28 18:37
@aseem2625 Here is a snippet

```typescript
// pages/api/vectordbqa.ts
export const config = {
  runtime: "edge",
};

export default async function handler(req: NextRequest) {
  // …
  // connect to pinecone
  const client = new PineconeClient();
  await client.init({
    apiKey: env.PINECONE_API_KEY,
    environment: env.PINECONE_ENVIRONMENT,
  });
  client.projectName = env.PINECONE_PROJECT_NAME;
  const vectorStore: VectorStore = await PineconeStore.fromExistingIndex(new OpenAIEmbeddings(), {
    pineconeIndex: client.Index(env.PINECONE_INDEX),
    namespace
  })
  // …
}
```

I’m doing the streaming similarly to https://github.com/hwchase17/langchainjs/blob/main/test-exports-vercel/src/pages/api/hello-edge.ts

**Comment by mweichert** [comment] 2023-05-04 17:01
I've found that this has to do with the axios-fetch-adapter:

```
async function getResponse(request, config) {
    let stageOne;
    try {
        stageOne = await fetch(request);
    }
    catch (e) {
        if (e && e.name === "AbortError") {
            return createError("Request aborted", config, "ECONNABORTED", request);
        }
        if (e && e.name === "TimeoutError") {
            return createError("Request timeout", config, "ECONNABORTED", request);
        }
        return createError("Network Error", config, "ERR_NETWORK", request);
    }
  //  ...
}
```

Does anyone know why the request is being adapted for fetch?

In any case,  from what I can see, fetch() cannot handle the request value as it throws with:
```
Adapter error TypeError: Only absolute URLs are supported
```

Anyone know how to fix this?

**Comment by nfcampos** [comment] 2023-05-05 10:04
@mweichert Can you share the full stack trace of the error you're getting? Where are you getting the error? Which environment are you running this on? Which version of langchain?

**Comment by avalanche-tm** [comment] 2023-05-06 09:38
I'm getting the same ERR_NETWORK on almost every request. Using langchainjs 0.0.70 and calling langchain in NextJS 13 API routes.

**Comment by nfcampos** [comment] 2023-05-06 14:48
@avalanche-tm As written in a previous comment https://github.com/hwchase17/langchainjs/issues/739#issuecomment-1504658534

> We actually test with NextJs before each release inside this repo, and I can confirm openai requests work in frontend components, api routes in serverless mode and api routes in edge mode. https://github.com/hwchase17/langchainjs/tree/main/test-exports-vercel/src/pages/api
> 
> I can also link you to this project which is using both of those (and the author tells me it works both locally and when deployed to vercel and fly.io) https://github.com/PineappleExpress808/lex-gpt/tree/main/pages/api
> 
> Do you want to compare your projects to this, and let me know what's different about yours? As it stands I cannot reproduce this issue, therefore can't help

**Closed** 2023-05-06 15:09 UTC

**Comment by nfcampos** [comment] 2023-05-06 15:19
For others with proxy setups/etc, langchain 0.0.71 now uses the default axios adapter in Node when not streaming (the openai sdk doesn't support streaming without a custom adapter, therefore when streaming we always use the fetch adapter).

**Comment by allanbritos** [comment] 2023-08-15 23:46
> 

@LarchLiu , what version of langchain are you using here and how did you implemented the agent? also in solution https://github.com/hwchase17/langchainjs/issues/388#issuecomment-1490421309, is 'https://proxy.your-server.com/v1'  an internet proxy or a reverse proxy to api.openai.com

**Comment by allanbritos** [comment] 2023-08-15 23:49
> For others with proxy setups/etc, langchain 0.0.71 now uses the default axios adapter in Node when not streaming (the openai sdk doesn't support streaming without a custom adapter, therefore when streaming we always use the fetch adapter).

@nfcampos , I just can't make the call to go through my internet proxy, I don't need to stream. Any advice? I'm using the langchain version 0.0.104
