### ISSUE TITLE
Bad Request 400 status code: "You must provide a model parameter" when attempting any openAI .call method

### ISSUE THREAD

**Issue by snapdeus** [hwchase17/langchainjs#336] opened 2023-03-15 12:57 UTC
Greetings,

**When using Node 18.1.0, or lower, on both Ubuntu 20.0.4 and Windows 10:**

Attempting to use the method `.call() ` results in a 400 status code. 
![image](https://user-images.githubusercontent.com/44621390/225312964-21f434c9-1981-4e99-8df5-1f322bc2d5a6.png)

Here is my code:

```
import { ChatOpenAI } from "langchain/chat_models"
import { HumanChatMessage } from 'langchain/schema'
import dotenv from 'dotenv'
dotenv.config()

const chat = new ChatOpenAI({
    openAIApiKey: process.env.OPENAI_API_KEY,
    temperature: 0.9

})
async function getChat() {
    const response = await chat.call([
        new HumanChatMessage(
            "Translate this sentence from English to French. I love programming."
        ),
    ]);


}

getChat()
```

Things I have tried: 

- Instead of passing the openAIApiKey as a parameter with .call(), I instead ran package.json script: `npm run dev` which was defined as `node -r dotenv/config index.js`
- Downgrading to Node 16.8.0 and setting NODE_ENV to experimental
- Downgrading the version of langchain to 0.0.22

### TEMPORARY SOLUTION

After changing my Node version to 18.2.0, the error does NOT happen! 

### What I suspect may be the cause:
Something with AxiosFetchAdapter...that's the only thing I can think of!

**Comment by nfcampos** [comment] 2023-03-15 13:26
Hi

In general it's not recommended to stick with old minor versions of Node. We only support running Langchain on the most recent versions of Node.js 16.x, 18.x, 19.x

**Comment by jacobcwright** [comment] 2023-05-09 05:26
Still getting this error with node v18.16.0

**Comment by nfcampos** [comment] 2023-05-09 09:24
Duplicate of #1010

**Closed by nfcampos** 2023-05-09 09:24 UTC
Labels: env/packaging

**Comment by Developergovind** [comment] 2023-11-01 09:03
same error
