### ISSUE TITLE
Chat History not beeing retrieved / saved

### ISSUE THREAD

**Issue by JeremyFabrikapp** [hwchase17/langchainjs#1339] opened 2023-05-20 01:32 UTC
Hi,
I am wondering if anyone else experience the same issue ?
I had some issues on my project and found out examples were returning an anomaly.

<img width="1069" alt="image" src="https://github.com/hwchase17/langchainjs/assets/78359496/1c25e4cc-246b-4016-bfd8-e5e2aca86449">

Buffer Memory is working fine.
<img width="685" alt="image" src="https://github.com/hwchase17/langchainjs/assets/78359496/7088d0f5-3f77-4b00-80bb-acbc4387507e">

I have noticed that the error appeared when model used was ChatOpenAI, but not when it is OpenAI. But in both case I can't seems to be able to save history.

**Comment by IanLeatherbury** [comment] 2023-05-21 04:10
I am running into the same issue, using the example from the documentation.

**Comment by jnebab** [comment] 2023-05-21 15:56
same issue also happening to me

**Comment by JeremyFabrikapp** [comment] 2023-05-21 16:56
@nfcampos did you notice this regression?

**Comment by IanLeatherbury** [comment] 2023-05-21 17:28
I was being silly – I am instantiating new instances of `BufferMemory`, `ChatOpenAI`, and `ConversationChain`, etc. when calling my API. I'll try Redis to persist the messages across sessions and report back if I run into any issues.

**Comment by rishitank** [comment] 2023-05-23 10:42
I am also seeing the same issue, regardless of using `ChatOpenAi` or `OpenAI`. I am currently using `RedisChatMessageHistory`, `BufferMemory` and `ConversationChain` and these are only instantiated once. If I call `await memory.loadMemoryVariables` I get `{ chat_history: '' }` every time.

**Comment by hgchrre** [comment] 2023-05-23 12:13
I have the same issue, specifically this only happens with the same setup as @rishitank. When not using `RedisChatMessageHistory` for the `BufferMemory` it seems to work. I checked and the chat history is being written to Redis however, so maybe the issue is on the fetching side.

**Comment by nfcampos** [comment] 2023-05-23 13:26
Thanks for reporting, this is fixed in #1374

**Comment by hgchrre** [comment] 2023-05-23 13:32
Greatly appreciated, thank you!

**Closed** 2023-05-23 15:35 UTC
