### ISSUE TITLE
New azure 2023-07-01-preview api version STREAMING is not supported

### ISSUE THREAD

**Issue by FrancescoMasaia** [hwchase17/langchainjs#2057] opened 2023-07-24 16:22 UTC
I'm currently trying to use the new 2023-07-01-preview api but when i set the streaming parameter to true the result in
generations is an empty array.

to test it is just necessary to use as configuration:
``` typescript
const llm = new ChatOpenAI({
    streaming: true,
    azureOpenAIApiDeploymentName: "GPT350613",
    azureOpenAIApiInstanceName: "...",
    // azureOpenAIApiVersion: "2023-05-15",
    azureOpenAIApiVersion: "2023-07-01-preview",
    azureOpenAIApiKey: "...",
    temperature: 0,
});
```

with streaming setted to false, it works perfectly

**Comment by jacoblee93** [comment] 2023-07-25 00:29
Thanks for raising this - it's a duplicate of #1914.

**Closed by jacoblee93** 2023-07-25 00:29 UTC
Labels: auto:bug
